export component FacePreview inherits Rectangle {
    in property<image> model-image;

    property<length> area: min(self.width, self.height) * 0.94;
    property<length> ox: (self.width - root.area) / 2;
    property<length> oy: (self.height - root.area) / 2;

    // 3D Shaded Solid Model Render
    Image {
        x: root.ox;
        y: root.oy;
        width: root.area;
        height: root.area;
        source: root.model-image;
        image-fit: contain;
    }
}
